# Generated by Django 5.0.1 on 2024-01-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("MyFirstApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
